[package]
name = "kvs"
version = "0.1.0"
authors = ["Luis Moreno <morenoluisma@gmail.com>"]
edition = "2018"
description = "KV ruStorage CLI"

[[bin]]

name = 'kvs'
test = false
doctest = true

[dependencies]
clap = {version = "~2.33.0", features = ["yaml"]}

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"

