name: Benchmark
on:
  push:
    branches: [ master ]
jobs:
  Benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/checkout@v2
      - name: Ready cache
        run: sudo chown -R $(whoami):$(id -ng) ~/.cargo/
      - name: Cache cargo
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
      - name: Run benchmark
        run: cargo bench -- --output-format bencher | tee output.txt
      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: Compare benchmarks
        uses: morenol/github-action-benchmark@v1
        with:
          tool: cargo
          output-file-path: output.txt
          external-data-json-path: ./cache/benchmark-data.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-always: true
          auto-push: false
          fail-on-alert: true
          alert-comment-cc-users: '@morenol'
      - name: Install cargo-cache
        uses: actions-rs/install@v0.1
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          crate: cargo-cache
          use-tool-cache: true
      - name: Cleanup cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo cache -a

